### ISSUE TITLE
Chord highlight problem

### ISSUE THREAD

**Issue by anviqs** [FUSAKLA/gdocs-songbook#8]
![Captura de tela 2024-03-10 092400](https://github.com/FUSAKLA/gdocs-songbook/assets/162885531/2d50ffca-839f-471a-9feb-b9056969c7ae)
There´s an issue when trying to highlight chords that are between | or / characters, if this could be fixed or add an option to manually highlight chords, would be great.
Thanks for your attention

**Comment by FUSAKLA** [comment]
Hi, it's a bit tricky since the plugin must somehow distinguish the chords from lyrics and this is done mainly by expecting some spaces around it etc. 
But I'll give it a try to handle such a case.

The other option you mention, manual highlight, sounds interesting. 
How exactly would you imagine it? That you would select some text and click some `highlight` button?

**Comment by FUSAKLA** [comment]
Hmmmm so… I can make it work, BUT 
it will highlight the whole line, not just the chords between the other symbols, so like this:
![image](https://github.com/FUSAKLA/gdocs-songbook/assets/6112562/85c9b519-4022-4329-b7cd-ca47be290bee)


I know it is not great, but unfortunately it's not trivial in the Google app script to color just part of the line (paragraph) :/

I'll ship this since it is still better than nothing, but let me know if this is OK with you.

**Comment by FUSAKLA** [comment]
Should be released with the above mentioned fix

**Comment by FUSAKLA** [comment]
Ok, I'll mark it as resolved and feel free to reopen the issue
